import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Swap from "../src/components/Swap";
import Navbar from "../src/components/Navbar";

import { useReadContract } from 'wagmi'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Santa Swap</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className={styles.header}>
        <Navbar />
      </header>

      <main className={styles.main}>

        <h1 className={styles.title}>Quick Swap</h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Swap />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
